name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  db_migrations:
    name: Run Supabase Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Supabase CLI
        run: |
          curl -sL https://get.supabase.com/cli | bash
      - name: Supabase DB Push
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: supabase db push --project-ref $SUPABASE_URL

  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: db_migrations
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Build Application
        run: npm run build

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod --confirm
